apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    openshift.io/scc: hostaccess
  name: node-observability-agent
spec:
  template:
    spec:
      containers:
      - image: quay.io/skhoury/node-observability-agent:go-latest
        imagePullPolicy: Always
        name: node-observability-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef: 
              fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /var/run/crio/crio.sock
          name: socket
          readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: ubi-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/crio/crio.sock
          type: Socket
        name: socket
