---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubi-scc-role
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["scc-admin"]
  verbs: ["use"]
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubi-scc-rb
subjects:
- kind: ServiceAccount
  name: $(SERVICE_ACCOUNT_NAME)
roleRef:
  kind: Role
  name: ubi-scc-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubi-scc-clusterrole
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs: ["get", "list"]
- nonResourceURLs: [ "/debug/pprof/profile"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubi-scc-crb
subjects:
- kind: ServiceAccount
  name: $(SERVICE_ACCOUNT_NAME)
  namespace: $(SERVICE_ACCOUNT_NAMESPACE)
roleRef:
  kind: ClusterRole
  name: ubi-scc-clusterrole
  apiGroup: rbac.authorization.k8s.io
