apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0002
  labels:
    app: ubi
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv0002

